---
- name: Manage ssh key
  hosts: "{{ host_name | default('all') }}"
  gather_facts: false

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: "{{ state }}"
        key: "{{ lookup('file', '{{ key_file }}') }}"
      when: key_file is defined
      

    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: "{{ state }}"
        key: "https://github.com/{{ github_account }}.keys"
      when: github_account is defined


    - name: Set authorized keys taken from variable
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: "{{ state }}"
        key: https://github.com/{{ ssh_key }}.keys
      when: ssh_key is defined
