---
- name: change DNS to shecan
  hosts: "{{ host_name | default('all') }}"
  become: true

  tasks:
    # Netplan
    - name: Read netplan config file
      when: ansible_distribution == "Ubuntu"
      shell: cat /etc/netplan/50-cloud-init.yaml
      register: netplan_config

    - name: replace DNS in netplan
      when: ansible_distribution == "Ubuntu" and netplan_config.stdout.find('nameservers') != -1
      ansible.builtin.replace:
        dest: /etc/netplan/50-cloud-init.yaml
        after: 'nameservers\:\n\s+addresses\:'
        regexp: \'((\d{1,3}\.{0,1}){4}\',\'(\d{1,3}\.{0,1}){4})\'
        before: "]"
        replace: "'178.22.122.100','185.51.200.2'"
        backup: yes

    - name: Validate netplan file
      when: ansible_distribution == "Ubuntu" and netplan_config.stdout.find('nameservers') != -1
      shell: /usr/sbin/netplan generate
      register: result

    - name: Apply netplan
      when: ansible_distribution == "Ubuntu" and result.stdout == ""
      shell: /usr/sbin/netplan apply
    
    # Others
    - name: Update Redhat or Debian
      when: ansible_distribution != "Ubuntu"
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 178.22.122.100
          nameserver 185.51.200.2
