---
- name: update packages
  hosts: "{{ host_name | default('all') }}"
  become: true

  tasks:
    - name: APT update
      when: ansible_os_family == "Debian"
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400

    - name: YUM update
      when: ansible_os_family == "RedHat"
      yum:
        name: '*'
        state: latest
        exclude: kernel*
