---
- name: Install docker
  hosts: "{{ host_name | default('all') }}"

  tasks:
    - name: Delete old script if already exists
      file:
        state: absent
        path: /tmp/install_docker.sh
  
    - name: Download installation script
      get_url: 
        url: https://get.docker.com 
        dest: /tmp/install_docker.sh
        mode: 0755
  
    - name: Install docker
      shell: /tmp/install_docker.sh
  
    - name: Delete installation script
      file:
        state: absent
        path: /tmp/install_docker.sh
