---
- name: Install cloudflare SSL tool
  hosts: "{{ host_name | default('all') }}"

  tasks:
    - name: Download CFSSL
      get_url:
        url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
        dest: /usr/local/bin/cfssl
        mode: 0755

    - name: Download CFSSL JSON
      get_url:
        url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
        dest: /usr/local/bin/cfssljson
        mode: 0755

    - name: Verfiy installation
      shell: /usr/local/bin/cfssl version
