---
- name: Install custom package with yum or apt
  hosts: "{{ host_name | default('all') }}"

  tasks:
    - name: 
      when: ansible_distribution == "RedHat"
      yum: 
        name: "{{ package_name }}"
        state: latest

    - name: 
      when: ansible_distribution == 'Debian' or ansible_distribution == "Ubuntu"
      apt: 
        name: "{{ package_name }}"
        state: latest
